version: '3.9'

services:
  java_app:
    container_name: projectify_app
    image: pjt-java-app:1.0.0
    build: .
    ports:
      - 2020:2020
    environment:
      - SPRING_DATASOURCE_URL = jdbc:postgresql://dpg-cnnik5779t8c739idl5g-a.oregon-postgres.render.com:5432/projectify
      - SPRING_DATABASE_USERNAME = projectify_dev
      - SPRING_DATABASE_PASSWORD = gfFcYdpWUGWCce5Tsz0NehEZTssmlija
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Andres1738
      POSTGRES_DB: Projectify
