version: '3.9'

services:
  java_app:
    container_name: projectify_app
    image: pjt-java-app:1.0.0
    build: .
    ports:
      - 2020:2020
    environment:
      - SPRING_DATASOURCE_URL = jdbc:postgresql://java_db:5432/Projectify
      - SPRING_DATABASE_USERNAME = postgres
      - SPRING_DATABASE_PASSWORD = Andres1738
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Andres1738
      POSTGRES_DB: Projectify
